sonar.projectKey=EventPulse
sonar.projectName=EventPulse
sonar.sources=app
sonar.tests=tests
sonar.python.coverage.reportPaths=coverage.xml
sonar.sourceEncoding=UTF-8

sonar.exclusions=alembic/**,.venv/**,coverage.xml,**/__pycache__/**,.pytest_cache/**,.mypy_cache/**,.ruff_cache/**
sonar.test.exclusions=.venv/**,**/__pycache__/**,.pytest_cache/**,.mypy_cache/**,.ruff_cache/**
