fullnameOverride: eventpulse
replicaCount: 2

image:
  repository: ghcr.io/abhi002shek/eventpulse
  digest: sha256:5b435783951d5878fb836e82fcd3e8a6d3b0986387e95f08dde4b984a26a21fb
  pullPolicy: IfNotPresent

serviceAccount:
  create: true
  automountServiceAccountToken: false

service:
  type: ClusterIP
  port: 8000
  targetPort: 8000

monitoring:
  enabled: false
  prometheusNamespace: monitoring
  serviceMonitor:
    enabled: false
    interval: 30s
    scrapeTimeout: 10s
    labels:
      release: eventpulse-observability
  prometheusRule:
    enabled: false
    labels:
      release: eventpulse-observability
    latencyThresholdSeconds: 0.5
    highErrorRatio: 0.05

ingress:
  enabled: true
  className: alb
  path: /
  pathType: Prefix
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}]'
    alb.ingress.kubernetes.io/healthcheck-path: /health
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
    alb.ingress.kubernetes.io/success-codes: "200"
    alb.ingress.kubernetes.io/target-group-attributes: deregistration_delay.timeout_seconds=30

config:
  environment: aws-dev
  logLevel: INFO

database:
  host: ""
  port: 5432
  name: eventpulse
  user: eventpulse
  sslMode: require
  secretName: eventpulse-database
  usernameKey: username
  passwordKey: password
  secret:
    create: false
    name: eventpulse-database
    usernameKey: username
    passwordKey: password
    password: ""
  externalSecret:
    enabled: true
    secretProviderClassName: eventpulse-database
    secretArn: ""
    region: ap-south-1
    usePodIdentity: "true"
    mountPath: /mnt/secrets-store
  networkPolicyEgressCidrs: []

postgresql:
  enabled: false

migration:
  enabled: true
  backoffLimit: 3
  activeDeadlineSeconds: 600

seed:
  enabled: true
  backoffLimit: 2
  activeDeadlineSeconds: 300

hpa:
  enabled: false

pdb:
  enabled: true
  minAvailable: 1

networkPolicy:
  enabled: true
  apiIngressCidrs: []

helmTests:
  enabled: true
