{{- if .Values.migration.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "eventpulse.fullname" . }}-migration
  labels:
    {{- include "eventpulse.labels" . | nindent 4 }}
    app.kubernetes.io/component: migration
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  backoffLimit: {{ .Values.migration.backoffLimit }}
  activeDeadlineSeconds: {{ .Values.migration.activeDeadlineSeconds }}
  template:
    metadata:
      labels:
        {{- include "eventpulse.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: migration
    spec:
      restartPolicy: Never
      automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
      serviceAccountName: {{ include "eventpulse.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: migration
          image: {{ include "eventpulse.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - alembic
            - upgrade
            - head
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          envFrom:
            - configMapRef:
                name: {{ include "eventpulse.fullname" . }}-config
          env:
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "eventpulse.secretName" . }}
                  key: {{ include "eventpulse.databasePasswordKey" . }}
            {{- if include "eventpulse.databaseUsernameKey" . }}
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "eventpulse.secretName" . }}
                  key: {{ include "eventpulse.databaseUsernameKey" . }}
            {{- end }}
          {{- if .Values.database.externalSecret.enabled }}
          volumeMounts:
            - name: external-database-secret
              mountPath: {{ .Values.database.externalSecret.mountPath | quote }}
              readOnly: true
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- if .Values.database.externalSecret.enabled }}
      volumes:
        - name: external-database-secret
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: {{ required "database.externalSecret.secretProviderClassName is required when database.externalSecret.enabled=true" .Values.database.externalSecret.secretProviderClassName | quote }}
      {{- end }}
{{- end }}
