{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "eventpulse.fullname" . }}-api
  labels:
    {{- include "eventpulse.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "eventpulse.apiSelectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector: {}
      ports:
        - protocol: TCP
          port: 8000
    {{- if and .Values.monitoring.enabled .Values.monitoring.serviceMonitor.enabled }}
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Values.monitoring.prometheusNamespace | quote }}
      ports:
        - protocol: TCP
          port: 8000
    {{- end }}
    {{- range .Values.networkPolicy.apiIngressCidrs }}
    - from:
        - ipBlock:
            cidr: {{ . | quote }}
      ports:
        - protocol: TCP
          port: 8000
    {{- end }}
  egress:
    - to:
        - podSelector:
            matchLabels:
              {{- include "eventpulse.selectorLabels" . | nindent 14 }}
              app.kubernetes.io/component: postgres
      ports:
        - protocol: TCP
          port: 5432
    {{- range .Values.database.networkPolicyEgressCidrs }}
    - to:
        - ipBlock:
            cidr: {{ . | quote }}
      ports:
        - protocol: TCP
          port: 5432
    {{- end }}
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
{{- end }}
