{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.database.host }}
  labels:
    {{- include "eventpulse.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.postgresql.service.port }}
      targetPort: postgres
      protocol: TCP
      name: postgres
  selector:
    {{- include "eventpulse.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
{{- end }}
