{{- if .Values.database.externalSecret.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ required "database.externalSecret.secretProviderClassName is required when database.externalSecret.enabled=true" .Values.database.externalSecret.secretProviderClassName | quote }}
  labels:
    {{- include "eventpulse.labels" . | nindent 4 }}
spec:
  provider: aws
  parameters:
    usePodIdentity: {{ .Values.database.externalSecret.usePodIdentity | quote }}
    region: {{ .Values.database.externalSecret.region | quote }}
    objects: |
      - objectName: {{ required "database.externalSecret.secretArn is required when database.externalSecret.enabled=true" .Values.database.externalSecret.secretArn | quote }}
        objectType: "secretsmanager"
        jmesPath:
          - path: "username"
            objectAlias: "username"
          - path: "password"
            objectAlias: "password"
  secretObjects:
    - secretName: {{ include "eventpulse.secretName" . | quote }}
      type: Opaque
      data:
        - objectName: "username"
          key: {{ include "eventpulse.databaseUsernameKey" . | quote }}
        - objectName: "password"
          key: {{ include "eventpulse.databasePasswordKey" . | quote }}
{{- end }}
