{{- if .Values.database.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "eventpulse.secretName" . }}
  labels:
    {{- include "eventpulse.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if include "eventpulse.databaseUsernameKey" . }}
  {{ include "eventpulse.databaseUsernameKey" . }}: {{ .Values.database.user | quote }}
  {{- end }}
  {{ include "eventpulse.databasePasswordKey" . }}: {{ .Values.database.secret.password | quote }}
{{- end }}
